DROP TABLE IF EXISTS `t1ger_gangs`;
CREATE TABLE `t1ger_gangs` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(100) NOT NULL,
	`notoriety` INT(11) NOT NULL DEFAULT 0,
	`cash` INT(11) NOT NULL DEFAULT 0,
	`leader` VARCHAR(100) NOT NULL,
	`ranks` LONGTEXT DEFAULT NULL,
	`members` LONGTEXT DEFAULT NULL,
	`markers` LONGTEXT DEFAULT NULL,
	`disabled` TINYINT(1) NOT NULL DEFAULT 0,
	`rackets` LONGTEXT DEFAULT NULL,
	PRIMARY KEY (`id`)
);